"""Initial migration

Revision ID: 29741b0a91f6
Revises: 
Create Date: 2025-01-10 11:32:48.713210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29741b0a91f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imsi', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('rtt', sa.String(), nullable=True),
    sa.Column('upf', sa.String(), nullable=True),
    sa.Column('cpu', sa.String(), nullable=True),
    sa.Column('ram', sa.String(), nullable=True),
    sa.Column('bw_requested', sa.String(), nullable=True),
    sa.Column('bw_received', sa.String(), nullable=True),
    sa.Column('slice1_active_ues', sa.Integer(), nullable=True),
    sa.Column('slice2_active_ues', sa.Integer(), nullable=True),
    sa.Column('active_ues', sa.Integer(), nullable=True),
    sa.Column('admission_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###


    # id = Column(Integer, primary_key=True, index=True)
    # imsi = Column(String)
    # device = Column(String)
    # timestamp = Column(DateTime)
    # rtt = Column(String)
    # upf = Column(String)
    # cpu = Column(String)
    # ram = Column(String)
    # bw_requested= Column(String)
    # bw_received=Column(String)
    # slice1_active_ues = Column(Integer)
    # slice2_active_ues = Column(Integer)
    # active_ues = Column(Integer)
    # admission_flag=Column(Integer)
