"""create metrics table

Revision ID: bfcf5e37c05f
Revises: 
Create Date: 2025-07-05 23:37:25.428591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfcf5e37c05f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IMSI_UE1', sa.String(), nullable=True),
    sa.Column('waiting_time_UE1', sa.Integer(), nullable=True),
    sa.Column('time_requested_UE1', sa.Integer(), nullable=True),
    sa.Column('IMSI_UE2', sa.String(), nullable=True),
    sa.Column('waiting_time_UE2', sa.Integer(), nullable=True),
    sa.Column('time_requested_UE2', sa.Integer(), nullable=True),
    sa.Column('IMSI_UE3', sa.String(), nullable=True),
    sa.Column('waiting_time_UE3', sa.Integer(), nullable=True),
    sa.Column('time_requested_UE3', sa.Integer(), nullable=True),
    sa.Column('episode_done', sa.String(), nullable=True),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
